### ISSUE TITLE
Bundle size is so huge

### ISSUE THREAD

**Issue by minamme** [ideal-postcodes/address-finder-bundled#340]
Hi
I'm seeing that it's really a huge in size. Why so much dependencies like `axios, fsm, jsutil` which make it ~80kb iun size. Can I reduce to small size?

**Comment by cblanc** [comment]
Hey there, perhaps you can share how you're building it. Currently it weights in at 65kb https://bundlephobia.com/package/@ideal-postcodes/address-finder-bundled@4.0.1

Some of the weight comes from polyfills, transpiration, ie11 support, UMD - i.e. bundling config.

You can make it smaller by using the untranspiled build address-finder which ships a clean unstranspiled ESM build https://bundlephobia.com/package/@ideal-postcodes/address-finder@3.0.1. If you use the ESM build you can probably make it smaller still with some tree shaking in your build process and shared deps (axios, lodash). 

The rest of the weight weight comes from the features we've provided over the years to make AF more user friendly and robust in common use cases.

- axios is essential for getting AF to work in SSR environments like Angular and Next.js. It provides the same interface in both front and backend environments 
- fsm is tiny (<2kb) but provides a solid state machine to build an error free UI tool
- jsutil (along with the rest of AF) provides a bunch of other helpful things like, screen reader accessibility, React/Vue compatibility, request caching, etc

We've also open sourced our upstream libraries (core-interface, core-browser) and open api specs (openapi). If you don't need any of the above features you can use the raw JS client instead or make simple HTTP calls to populate a popular dropdown library.
