### ISSUE TITLE
IdealPostcodes.AddressFinder not working inside ajax block

### ISSUE THREAD

**Issue by khaledelmahdi** [ideal-postcodes/address-finder-bundled#415]
Hello,

I have a wizard page with multiple setps. Some of these steps has address fields.
The steps are loaded though ajax not page reload. (laravel + https://spatie.be/docs/laravel-livewire-wizard/v1/introduction)

Only the first step has the address lookup working, all other steps do not work. 

I have the javascript setup code on each step. No errors on the console.

Is there a way to force loading the address finder when loading the steps?

**Comment by cblanc** [comment]
Hey there

I suspect you're using `.setup()` which expects the address fields to be present in order to bind

You can try using `.watch()` instead, this will periodically check your page to see if any matching fields are present
